### ISSUE TITLE
Plot label

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/npms-app#10]
When you create a plot on the NPMS website, you can give a plot name (we advise people to label them numerically, but it is a free-text field). It would be good if we could display this information, as on the NPMS website (e.g. Plot 1 at SU4212887299 (Linear plot)). I know that you were thinking about a symbol to indicate plot type (linear / square 10 m / square 5 m), but do you think we could also display the plot “name”? I realise that this might create space challenges (because it is a free text field, and people could have given them long descriptive names, but presumably we could truncate these to a defined length for display)?

**Comment by sacrevert** [comment]
Yes, this is a good idea. I would be happy with truncated names (ending with an ellipsis '...' to indicate truncation). Only medium priority though I think.
