### ISSUE TITLE
[beta testing 2024] indicia registration fields required by app

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#101]
@andrewvanbreda Current response from NPMS app, presumably may affect PP too when that gets to this stage?

![image](https://github.com/user-attachments/assets/5b31f117-76b9-4768-8fc0-5b2e44249099)

**Comment by kazlauskis** [comment]
@sacrevert If we can't or don't want to relax the registration process then I can add these missing required fields to the app.

**Comment by sacrevert** [comment]
I have no preference, whatever @andrewvanbreda thinks is easiest for getting this working

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis @sacrevert 
I guess I don't have any opinion on the difficulty of getting something working, as it will be something Karolis needs to do.

However if you are wanting registration to be possible from the app (as apposed to some kind of system that directs the user to the website to fill in details), then I think the best thing to do is to add these fields to the app.
When that is done, we simply do a test registration and I will check the data has been automatically added to the Warehouse.
(this is necessary for the data to appearing on the User Information Download report)

**Comment by andrewvanbreda** [comment]
Note, that this is NPMS only.
The only none-standard field on Plant Portal is the Training flag

**Comment by sacrevert** [comment]
@andrewvanbreda perfect, let's go with adding the fields to the app where required then

**Comment by kazlauskis** [comment]
OK, I will add the missing fields to the NPMS registration page.

@andrewvanbreda can we enable "Registration with password" on the PP site too?

**Comment by andrewvanbreda** [comment]
@kazlauskis 
I cannot at this precise time due to differences in the way PP is setup, but I am working towards doing that with Biren's help.

**Comment by kazlauskis** [comment]
I've added the missing NPMS fields now. There is the other ticket for the PP, so closing this now.
