### ISSUE TITLE
Photo upload

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/npms-app#16]
When attaching a photo to a plot, the app allowed me to take one specifically for upload but it could not upload a photo that was already in my photo gallery (at least, I’m not sure if it uploaded or not, but if I clicked on the thumbnail it said “The image could not be loaded” on a black screen. Once it showed this black screen it then caused the app to go into meltdown, showing just the top blue bar and continuing to show a black screen with “the image could not be loaded” whatever I did. Had to force close the app to get a response. When reopened, the app could then scroll through “the image could not be loaded screens” without crashing, but still no images loaded.

**Comment by sacrevert** [comment]
@kazlauskis can this be closed?
