### ISSUE TITLE
Oli's text changes etc

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#18]
1. Management: some text lost by not showing multiple lines

2. Grazing: header says ‘ Which animals were grazing?’, but does not capture animal type, only intensity. Website captures both (animal type is free text).

3. Comment: Please add any extra info about this plot

4. Bare rock: On entry title changes to Gravel. Call both titles Bare rock etc. if Bare rock/gravel too long.

Other, main page:
5. Recorder Names: title changes to ‘Identifiers’ on opening. Stick with Recorder Names. Add the word ‘only’ to info text. i.e. ‘Please only add additional recorders here’

**Comment by kazlauskis** [comment]
Great, thanks, could you split such blocks to different tasks next time, it's easier to comment that way.

**Comment by kazlauskis** [comment]
The biggest issue with those text changes is that some are bit too long to fit in nicely. I had to remove the 'black bags' from 'Silage production (i.e. black bags)'.

**Comment by sacrevert** [comment]
@kazlauskis Can I close this now?
