### ISSUE TITLE
Niki's text changes

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#19]
>1. Might be worth adding in a sentence to “searching for species tab” just saying something like “searches can also be made using common plant names” so users don’t think they have to search solely for scientific names. 

Yes, please add “searches can also be made using common names” below the example scientific name abbreviations.

> 2. As I mentioned before, would be good to link to the full NPMS data access policy from the privacy page. On privacy page “This allows you to log in and see your records and those submitted by other people for all species”. Oli- this isn’t currently true yet, is it? As the reporting function for all species is not currently public? ... [truncated]

**Edits for Privacy Information:**
i)	Under ‘Who will have access to my personal data’, please add the word ‘these’ to ‘Unless required by law, these data will not be made available to any third parties… etc.” just to avoid ambiguity.
ii)	Under ‘Use of your name’, delete “and those submitted by other people for all species” from that sentence.
iii)	Under ‘Other information collected by the application’, just say Records will be made accessible to anyone on request.
iv)	Above ‘use of your name’ add a new section entitled ‘NPMS data access policy’, with the following text: “Please see the website for our full data access policy” [using the following link: http://www.npms.org.uk/content/data-access-policy-public ]. A following sentence should say “Surveyors should have read and accepted the NPMS data access policy on registering for the scheme”.

> 3. “How to make a new record” still TODO. Well spotted. I will update the text with Oli’s suggestions.

This section has been deleted now, no?

>4. I see in the privacy section that there is a bit about photo licensing. Technically, according to the MoA, any photos should be licensed under OGL, therefore reproducible by anyone (with attribution), not just by partners/scheme. I will leave this to Oli to review.

Please delete all of the current text in this section, and just state that “By submitting a photo with this app you agree to your photos being licensed under an Open Government Licence with attribution.” The OGL text can link out to the OGL licence. http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

**Comment by kazlauskis** [comment]
Yes, I have deleted the how to make a record though I can easily add it in if you want.

**Comment by sacrevert** [comment]
Presuming that this can be closed now.
