### ISSUE TITLE
Login page text

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#21]
From Claire Halpin:
 
>On the Login page, if you leave name or password blank, it displays an error 'can't be blank' in tiny letters under the name or password. It's not very user friendly - needs to be bigger or a separate message box. And the text is a bit unprofessional - the 'Required' message used for Location, Recorder names on the main page, although brief, looks better in my opinion.

**Comment by sacrevert** [comment]
Presumably not a quick fix

**Comment by kazlauskis** [comment]
Yeah, I think this isn't a big issue (if any) at the moment. I will try to make it slightly bigger if I have the time.
