### ISSUE TITLE
Recorder names error message

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#27]
From Claire Halpin:

>If I clear the Recorder names on the main Survey page, the error message I get says 'identifiers - missing' which is confusing. Should be 'Recorder names - missing'.

**Comment by sacrevert** [comment]
@kazlauskis a quick fix?

**Comment by kazlauskis** [comment]
Yeah, I will fix it.

**Comment by sacrevert** [comment]
@kazlauskis Can be closed?
