### ISSUE TITLE
sample:entered_sref error on submission

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/npms-app#38]
![img_2020](https://user-images.githubusercontent.com/7383162/30524715-9159d006-9bf0-11e7-9132-4d956585aa02.png)

**Comment by kazlauskis** [comment]
This part attaches the `entered_sref` to the submission in [this file](https://github.com/NERC-CEH/npms-app/blob/master/src/common/config/config.js#L101).

For some reason the `value.plot` must be empty or corrupted so that the warehouse rejects it then.

```javascript
location: {
        id: 'location_id',
        values(value, submission) {
          // add other location related attributes
          submission.fields.entered_sref = value.plot; // eslint-disable-line

          // lat lon
          if (value.plot.match(/\d+\.\d+N \d+\.\d+W/g)) {
            submission.fields.entered_sref_system = 4326; // eslint-disable-line
          }

          return value.id;
        },
}
```

**Comment by sacrevert** [comment]
@kazlauskis can this be closed?

**Comment by kazlauskis** [comment]
I will close it once the app is released in the apple app store

**Comment by sacrevert** [comment]
@kazlauskis Can this be closed?
