### ISSUE TITLE
In-app registration -- data access policy issues

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#39]
From @andrewvanbreda as a marker for future work
>The thing we would need to be careful of on the app is that we restrict usage unless the user has agreed to the data access policy. So there could still be a registration process.
I don't think this would be too much of a problem for new users as I think one of the things we will do is make setting the data agreement checkbox mandatory.....I assume that would be easy on the app.
However older users who haven't agreed would need to be restricted.  In theory we just check the value of the data agreement and restrict usage.....in practice there are a few things to consider (e.g. the information saying the user has checked the data access policy doesn't go immediately into the Indicia database....there is a delay until it is synced) Anyway, I don't think we need to worry about that too much right now, as David has said we aren't developing this further for now, perhaps this email will just be a note of things to consider in future.

**Comment by andrewvanbreda** [comment]
The user will now register with app and select the data access policy toggle. This then automatically selects the data access policy on the Drupal website. The user is then required to fill in their address on the website and at this point the data access agreement is synced to the Indicia Warehouse for display on the User Information Download

**Comment by sacrevert** [comment]
@andrewvanbreda Can this be closed?
