### ISSUE TITLE
Phone menu obscuring app menu

### ISSUE THREAD

**Issue by andrewvanbreda** [NERC-CEH/npms-app#40]
The purple menu bar accress the top of the screen is cutoff be mobile’s own black menu bar across the top of the screen. In the top right of the NPMS app I think it says “Survey”  but this is heavily obscured.
Android 6.0 phone

**Comment by sacrevert** [comment]
@kazlauskis do you think this is something that is likely to have been fixed as a result of recent work? Or is it just low priority as version 6.0 is fairly old now?

**Comment by kazlauskis** [comment]
Not sure, but I will have a look at this.
