### ISSUE TITLE
During registration on app I had to specify password twice

### ISSUE THREAD

**Issue by andrewvanbreda** [NERC-CEH/npms-app#44]
During registration on the App, I think it asked me for my password. 
However once I got the registration email, the website also asked me to enter a password too during registration, so perhaps we don’t need password field during app registration.

**Comment by andrewvanbreda** [comment]
Indicia API module now has its own NPMS app branch. This allows an administrator to specify a registration email that doesn't include a link to the password setup page (as it is already done on the app). The account is also auto-activated.

**Comment by DavidRoy** [comment]
@kazlauskis is this an idea to replicate for other Indicia apps?

**Comment by andrewvanbreda** [comment]
@DavidRoy @kazlauskis 
I haven't used any of your other apps, but there is nothing about this change that should limit it to NPMS only. If I remember correctly all the changes are in the Indicia API module for Drupal 7.
I suppose the only thing is it might need porting to the Drupal 8 version of the module if any projects are running Drupal 8.

**Comment by kazlauskis** [comment]
Yeah, this might be useful to have for other new apps that use the DP8 version of this module. As for other apps that use the DP7, it all works correctly. Say for the iRecord App, the verification email with a link is sent to new users and clicking the link then activates your account and sends a welcome email.
