### ISSUE TITLE
Highlight genus level records at Inventory level as per website

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#47]
See https://github.com/BiologicalRecordsCentre/NPMS/issues/161

**Comment by kazlauskis** [comment]
Would a warning next to each genus entry be OK here? Else, I can also add a popup upon submission if you preferred.

![Screenshot 2020-06-18 at 12 08 53](https://user-images.githubusercontent.com/7383162/85013452-81bd5d00-b15c-11ea-94d5-ab2b93854fb8.png)

**Comment by sacrevert** [comment]
Warning looks great, good thinking.
Maybe say "Please provide photo(s) to aid ID" though to encourage people to submit a selection of pics

**Comment by kazlauskis** [comment]
Great. The app allows only one picture per species at the moment so I will phrase it `Please provide a photo to aid ID` for now.

**Comment by kazlauskis** [comment]
Would it make sense to keep it consistent and show the same warning across all the surveys or would you like it just for the inventory survey?

**Comment by sacrevert** [comment]
At wildflower and indicator level the only genus level records allowed (in theory!) are those listed as NPMS indicators. These are all relatively difficult taxa, so the photos probably won't be that useful in those cases.

More generally though, we could display the warning for all taxa, across all survey levels, when the iRecord "ID difficulty" flag is at least level 2 (e.g. most grasses, like Poa annua). Is that straightforward? Should that be separate issue?

**Comment by kazlauskis** [comment]
The app currently doesn't have such information, but if it had then this would be great to show. Yes, please create another ticket.

**Comment by sacrevert** [comment]
@kazlauskis just to confirm, photos are being encouraged here, but should not be mandatory at this point (we can review this in future)
