### ISSUE TITLE
Photo uploads again

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#49]
Photo picker still appears to be broken on my phone. Cannot add photo directly from camera, but had to go via image gallery.

Android 8.1.0
Current version (build number): OPP28.85-19-4-2
Phone: Moto G5

**Comment by kazlauskis** [comment]
Sorry, I cannot replicate this. I have an older Moto G4 running Android 7 and it works fine just as well as with newer devices. The app asks for a permission to access your Gallery and Camera, have you granted that? You should be able to change/inspect this in the device settings -> Apps -> NPMS app -> Permissions.

When trying to use the take a photo with a camera when using the app, what does it show you? Crashes or just silently doesn't do anything? 

Are you using a custom camera app as a default camera on your device?

**Comment by sacrevert** [comment]
When I take a photo with standard camera it shows me the pic, I approve it, but then it doesn't appear on the sample. The permissions list doesn't give the camera, closest is SD card access (even when I have expanded to see all permissions)

**Comment by kazlauskis** [comment]
Thanks, this is very useful.
