### ISSUE TITLE
Add resources page

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#62]
Page of links to other AI apps:

- [x] Title
"Recommended resources"
- [x] Body text to describe the page
"You may find the below apps useful for plant ID and field navigation"
1. "Plant ID" 
- [x] PlantNet: https://apps.apple.com/gb/app/plantnet/id600547573
- [x] Flora Incognita:
https://play.google.com/store/apps/details?id=com.floraincognita.app.floraincognita&hl=en_GB&gl=US
- [x] Seek:
https://www.inaturalist.org/pages/seek_app
2. "Navigation and others" 
- [x] Grid Ref app:
https://play.google.com/store/apps/details?id=net.blerg&hl=en_GB&gl=US
- [x] iRecord app:
https://irecord.org.uk/app/

**Comment by sacrevert** [comment]
@sacrevert @NPMSsupport @kwal2 to provide list of specific links

**Comment by kwal2** [comment]
Free one that I use and seems to work well is Flora Incognita
https://play.google.com/store/apps/details?id=com.floraincognita.app.floraincognita&hl=en_GB&gl=US

**Comment by sacrevert** [comment]
@kazlauskis updated
