### ISSUE TITLE
PDF map access through app

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#63]
PDF map access through app?

**Comment by kazlauskis** [comment]
@sacrevert what is the PDF you would like me to embed into the app?

**Comment by sacrevert** [comment]
@kazlauskis Maps for squares have the following URL form:
https://www.npms.org.uk/sites/default/files/PDF/squares/NR4651.pdf
So, the PDF name is the location name of the square.

**Comment by kazlauskis** [comment]
Thanks, I think, have misinterpreted the requirement here. Can you explain a bit more how/where would you like the app to display these PDFs?

**Comment by sacrevert** [comment]
That's OK, I don't think we thought this item would get done under the current subcontract from PL anyway. (Unless I am forgetting something). 

The idea is that it is just a convenience option for the user. So, I imagine it would perhaps just be a separate option from the main page, in the way that the map of the British Isles is in the iRecord app. That is to say, it doesn't really matter where it goes in terms of the "flow" of the survey, because the user should already have set up their plots, and providing the map is just for convenience in case they want to look back at it at any time.

**Comment by kazlauskis** [comment]
So as far as I understand these are user-selected squares that appear in the locations list when doing a survey. What if we added a link to the PDFs next to the square name? Would this be OK if this worked online only?

Also, does every square has a matching PDF? Like in this example we have a square in Ireland that seems to have a PDF but I haven't tried the Channel Islands or other places yet.

<img width="329" alt="Screenshot 2021-04-07 at 13 53 40" src="https://user-images.githubusercontent.com/7383162/113869709-f1164300-97a8-11eb-8af1-369b26ceb7e4.png">

**Comment by sacrevert** [comment]
Yes, that's fine linkwise. In theory every square in the survey currently should have a PDF/URL based on the square lettered grid ref name.
