### ISSUE TITLE
Add DAERA-NI logo to launch screen credits

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#70]

**Comment by kazlauskis** [comment]
Do you have the logo in PNG or a similar format?

**Comment by sacrevert** [comment]
![A4 DAERA Logo Black Spot](https://user-images.githubusercontent.com/5985134/116523572-4936f580-a8ce-11eb-9a1c-77483b2ea7c5.png)

**Comment by sacrevert** [comment]
Here you go
[A4 DAERA Logo Black Spot.zip](https://github.com/NERC-CEH/npms-app/files/6397269/A4.DAERA.Logo.Black.Spot.zip)
