### ISSUE TITLE
[beta testing 2024] Training mode banner also on survey pages

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#72]
It would be nice if, in the future, the training mode banner was also shown on the individual "Survey" pages (i.e. the one with the submit button), as well as on the main app screen.

**Comment by kazlauskis** [comment]
In general, I avoid using too much page space for informational elements and allow more of the actual survey to be visible. Also, adding the "training" banner to all survey pages is tricky as many of these are standard components that I would have to tweak and might look inconsistent across the pages. I wonder if something simpler would work, like adding a black banner to the survey item in the survey list (like we do for the iRecord App) or making the "training" banner bigger for the front survey page. I could also show a popup to remind this is a training survey when opening it up. 


![Screenshot 2024-10-04 at 09 15 13](https://github.com/user-attachments/assets/ea4000cf-1774-4a7c-bc6c-380230773142)

**Comment by sacrevert** [comment]
>I wonder if something simpler would work, like adding a black banner to the survey item in the survey list (like we do for the iRecord App) or making the "training" banner bigger for the front survey page. I could also show a popup to remind this is a training survey when opening it up.

If not too much hassle, maybe we could do all of these?

**Comment by kazlauskis** [comment]
Sure, will do.
