### ISSUE TITLE
Species photos not being loaded

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#73]
Plot photos are ok, but species photos do not seem to be being loaded

**Comment by kazlauskis** [comment]
Thanks, I'll have a look at it asap.

**Comment by kazlauskis** [comment]
@sacrevert I am trying to replicate this. Do you have a sample ID of a record that doesn't show the photos?

**Comment by sacrevert** [comment]
It's not this, it's that the photo is not attached to the record at all after I take it with the camera. Also, on my phone, the gallery option doesn't work, it also takes one to the camera. (However, both work fine for plot photos, so I assume it is not something about my phone or OS)

**Comment by kazlauskis** [comment]
Thanks, I can reproduce some of it now.

**Comment by kazlauskis** [comment]
Just to say that I'm still on it. It has snowballed into some more library updates and framework fixes.

**Comment by sacrevert** [comment]
Appreciated, thanks!

**Comment by kazlauskis** [comment]
That's fixed now. The new version will be 1.4.1.

**Comment by sacrevert** [comment]
Thanks very much! Apologies for missing that during the testing.

**Comment by kazlauskis** [comment]
No prob, we've all missed this 😄
