### ISSUE TITLE
[beta testing 2024] White navigation buttons on Android devices

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#79]
These issues don't see to have been fixed as of beta v. 2.0.0

They are:
(1) Wrong logo on initial launch screen on loading app for first time (transparent NPMS only logo being used)
(2) Transparent and wrong logo used for app on Android
(3) Android navigation buttons invisible on many app pages (white on white)

Screenshots:
[Photos-001 (1).zip](https://github.com/user-attachments/files/16248922/Photos-001.1.zip)

**Comment by sacrevert** [comment]
Resolved by v.2.0.0(48)

**Comment by sacrevert** [comment]
@kazlauskis the white phone menu buttons on a white background seems to have come back again on my Android phone. I noticed the same thing for the launched version of the e-surveyor app yesterday too. Can we fix this? For example:

![image](https://github.com/user-attachments/assets/e50fb8a3-9c45-4645-a638-95be046e7889)

**Comment by kazlauskis** [comment]
Thanks, I'll fix this.
