### ISSUE TITLE
[beta testing 2024] Intro text confusion re login/registration

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#81]
Intro text states that you need to already have an NPMS or PP account to use the app, but then later there is an option to login OR register.

IIRC correctly, app stores require in-app registration possibility, so maybe we just need to tweak misleading intro text?

**Comment by kazlauskis** [comment]
@sacrevert I can remove the account registration if that's preferrable, but I suggest to keep the functionality in the app and edit the texts instead (can you provide me the new texts?).

**Comment by sacrevert** [comment]
I can, but I can't seem to generate the existing screen with the text, even after uninstalling and reinstalling. Can you provide a screenshot?

**Comment by kazlauskis** [comment]
![Screenshot 2024-10-04 at 09 23 32](https://github.com/user-attachments/assets/7f876e0a-cf7e-4863-873b-72ec40001dfa)
![Screenshot 2024-10-04 at 09 23 37](https://github.com/user-attachments/assets/030287a1-cf34-44ec-a075-bab0cbe32279)
![Screenshot 2024-10-04 at 09 23 43](https://github.com/user-attachments/assets/2b8f788e-8466-43d2-b0b8-7976418240cd)
![Screenshot 2024-10-04 at 09 23 50](https://github.com/user-attachments/assets/74551301-cb95-4d0c-9d57-2d8aed49553f)

**Comment by sacrevert** [comment]
Actually, I think this is fine tbh. Thanks for the screenshots!
