### ISSUE TITLE
[beta testing 2024] More text on splash screen

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#84]
Some folk found the opening screen lacking in information (the one saying "Choose your portal". 

Perhaps we can add the following text below "Choose your portal" in a slightly smaller font size.

"For core NPMS choose the NPMS button. For NPMS+ and standard Plant Portal usage, choose the Plant Portal button.

Logging out of your chosen website will return you to this screen."

**Comment by kazlauskis** [comment]
Would this be OK?

<img width="378" alt="Screenshot 2024-10-03 at 16 37 34" src="https://github.com/user-attachments/assets/1181f1b7-6ff1-4bcd-a4e8-a9493e937ad9">

**Comment by sacrevert** [comment]
Perfect
