### ISSUE TITLE
[beta testing 2024] NPMS menu item

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#94]
In the main NPMS menu, under "Info", can we add a new entry with the name "My Data"

The text within this option will be as follows:
"If you are already signed in to your NPMS account online, you can access all of your submitted data via the following link: https://www.npms.org.uk/content/my-visits"

**Comment by kazlauskis** [comment]
<img width="370" alt="Screenshot 2024-10-03 at 16 27 03" src="https://github.com/user-attachments/assets/b10bd3a5-bbc0-483e-81d4-e3cefc44f52d">

**Comment by kazlauskis** [comment]
Should this be a button that shows a popup? Or should we simply redirect the users to the NPMS page? Also should we show something similar to PP users?

**Comment by sacrevert** [comment]
Good point. For PP the text should be:

"If you are already signed in to your Plant Portal account online, you can access all of your submitted data via the following link: https://plantportal.ceh.ac.uk/data-download"

I don't have a strong opinion about popup versus redirect, I would do whichever is easier (I assume redirect?)
