### ISSUE TITLE
[beta testing 2024] NPMS survey drafts bug and possible enhancement

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#95]
I'm not sure whether this is achievable within budget, but at the moment one is only allowed one listed survey draft, and opening a new survey, whether at the same survey level or different, either results in discarding the existing or continuing.

The latter part of this is an important bug, as it means that even if one chooses a different survey level from the existing one that could be continued, if one chooses continue, one ends up editing a survey at a different level to the one initially selected (e.g. I select Wildflower, I get the message about continuting with an existing survey, but this is Inventory, I click continue and end up on an Inventory survey.

Can all draft surveys be kept and labelled with their Location, if that has been selected?

**Comment by kazlauskis** [comment]
@sacrevert I can enable multiple drafts so users won't be prompted to finish existing ones and can have several draft surveys at the same time. Would that be OK?

**Comment by sacrevert** [comment]
Yes, that sounds sensible. Cheers!
