### ISSUE TITLE
[beta testing 2024] Photo captions

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#98]
This may be beyond budget, but is it possible to enable captions for photos?

**Comment by kazlauskis** [comment]
@sacrevert, yes, I can add this in. The simplest way would be to add a text field to the full-screen photo view. Would something like this be OK?
![Screenshot 2024-10-03 at 15 39 19](https://github.com/user-attachments/assets/35a4533b-b5fa-474e-9aea-d14f539c5a52)

![Screenshot 2024-10-03 at 15 39 14](https://github.com/user-attachments/assets/73cdaceb-804c-4612-b603-f3646c9aff8e)

**Comment by sacrevert** [comment]
Perfect!
